name: Go
on: [push]

jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#       - name: Setup Go
#         uses: actions/setup-go@v5
#         with:
#           go-version: '1.22.x'
#       - name: Test with the Go CLI
#         run: go test ./...
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Format
        run: go fmt ./...
      - name: Golangci Linter
        uses: golangci/golangci-lint-action@v6