name: Go
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Format
        run: go fmt ./...
      - name: Golangci Linter
        uses: golangci/golangci-lint-action@v6